### PR TITLE
Add data files for Run 2 Scouting data format unit test

### PR DESCRIPTION
**Pull request by wddgit**
Add data files for Run 2 Scouting data format unit test

### CODE REVIEW

**Comment by wddgit** [comment]
please test

I'll submit a separate PR to the CMSSW DataFormats/Scouting package soon. The unit test in that other PR is what really tests this PR. This just contains data files used in the test in the other PR.

**Comment by smuzaffar** [comment]
+core

**Comment by smuzaffar** [comment]
+externals

**Comment by smuzaffar** [comment]
this can already go in to IBs as its only adds new data files

**Comment by perrotta** [comment]
+1

**Pull request merged**
