### PR TITLE
Add data file for update of Scouting DataFormats in CMSSW_14_0_0_pre3

### PR DESCRIPTION
**Pull request by mmusich**
To address https://github.com/cms-sw/cmssw/issues/43755.
Needed for https://github.com/cms-sw/cmssw/pull/43856

Update includes: 
 - `Run3ScoutingElectron` (version 7)
 - `Run3ScoutingPhoton` (version 6)
 - `Run3ScoutingVertex` (version 4)

### CODE REVIEW

**Comment by smuzaffar** [comment]
+externals

**Comment by makortel** [comment]
+core

**Comment by mmusich** [comment]
https://github.com/cms-sw/cmssw/pull/43856 was merged, so this PR needs to be merged as well.

**Comment by smuzaffar** [comment]
Merging this now

**Pull request merged**
